INSERT INTO style_tags(tag_name) VALUES ('Современный');
INSERT INTO style_tags(tag_name) VALUES ('Скандинавский');
INSERT INTO style_tags(tag_name) VALUES ('Лофт');
INSERT INTO style_tags(tag_name) VALUES ('Классический');
INSERT INTO style_tags(tag_name) VALUES ('Минимализм');
INSERT INTO style_tags(tag_name) VALUES ('Средиземноморский');
INSERT INTO style_tags(tag_name) VALUES ('Бохо');
INSERT INTO style_tags(tag_name) VALUES ('Рустик');
INSERT INTO style_tags(tag_name) VALUES ('Винтаж');
INSERT INTO style_tags(tag_name) VALUES ('Эклектика');
INSERT INTO style_tags(tag_name) VALUES ('Индастриал');
INSERT INTO style_tags(tag_name) VALUES ('Фьюжн');
INSERT INTO style_tags(tag_name) VALUES ('Традиционный');
INSERT INTO style_tags(tag_name) VALUES ('Тропический');
INSERT INTO style_tags(tag_name) VALUES ('Французский провинциальный');
INSERT INTO style_tags(tag_name) VALUES ('Морской');
INSERT INTO style_tags(tag_name) VALUES ('Арт-деко');
INSERT INTO style_tags(tag_name) VALUES ('Модерн');
INSERT INTO style_tags(tag_name) VALUES ('Голливудский гламур');
INSERT INTO style_tags(tag_name) VALUES ('Колониальный');
INSERT INTO style_tags(tag_name) VALUES ('Шебби-шик');
INSERT INTO style_tags(tag_name) VALUES ('Азиатский');
INSERT INTO style_tags(tag_name) VALUES ('Юго-западный');
INSERT INTO style_tags(tag_name) VALUES ('Готический');
INSERT INTO style_tags(tag_name) VALUES ('Ретро');

INSERT INTO roles(role) VALUES ('ADMIN');
INSERT INTO roles(role) VALUES ('USER');
INSERT INTO roles(role) VALUES ('DESIGNER');
